# Analysis options for AI Chatbot Mobile Client
# Uses flutter_lints for recommended lint rules

include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "lib/generated/**"

linter:
  rules:
    - prefer_single_quotes
    - require_trailing_commas
    - sort_child_properties_last
    - use_key_in_widget_constructors
    - prefer_const_constructors
    - prefer_const_declarations
    - avoid_print
    - avoid_unnecessary_containers
    - sized_box_for_whitespace
    - use_build_context_synchronously
    - cancel_subscriptions
    - close_sinks
    - always_declare_return_types
    - annotate_overrides
    - avoid_empty_else
    - prefer_final_locals
    - unnecessary_this
    - unnecessary_new
    - prefer_is_empty
    - prefer_is_not_empty
