import 'package:freezed_annotation/freezed_annotation.dart';

import 'message_sender.dart';
import 'message_status.dart';

part 'message.freezed.dart';

/// A single chat message exchanged between the user and the AI.
///
/// Immutable value object generated by Freezed.
/// Use `copyWith` to derive modified instances (e.g., appending streamed
/// content or updating [status]).
@freezed
abstract class Message with _$Message {
  const factory Message({
    /// Unique identifier (UUID).
    required String id,

    /// Text content of the message.
    required String content,

    /// Who sent this message.
    required MessageSender sender,

    /// When the message was created or received.
    required DateTime timestamp,

    /// Parent conversation this message belongs to.
    required String conversationId,

    /// Current lifecycle status.
    required MessageStatus status,

    /// Elapsed time in milliseconds for a completed bot response.
    /// Only populated when [status] is [MessageStatus.complete] and
    /// [sender] is [MessageSender.bot].
    int? responseTimeMs,
  }) = _Message;
}
